Web/library_app/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :authors
  resources :items
  resources :roles
  resources :users
  resources :sessions
  resources :searches

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  root 'welcome#index'

end

Web/library_app/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :authors

  def self.search(query)
    where("title like ?", "%#{query}%")
  end
end

Web/library_app/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  # GET /items
  # GET /items.json


  def index
    if params[:search]
      @items = Item.search(params[:search]).order("created_at DESC")
    else
      @items = Item.all.order('created_at DESC')
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to "http://localhost:3000/items/#{@item.id}", notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to "http://localhost:3000/items/", notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to "http://localhost:3000/items/", notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :ISBN, :Description, :author, :avaliability)
    end

Web/library_app/app/helpers/items_helper.rb
module ItemsHelper
end

Web/library_app/app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :author, "Select Author" %><br>
    <%= f.select(:author, Author.all.collect {|p| [ p.name, p.id ] }) %>
  </div>

  <div class="field">
    <%= f.label :ISBN %><br>
    <%= f.text_field :ISBN %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_field :Description %>
  </div>
    <div class="field">
    <%= f.label :avaliable, "Avaliablility" %><br>
    <%= f.check_box :avaliability %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Web/library_app/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

Web/library_app/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
  <%= form_tag items_path, :method => 'get' do %>
  <p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
      <th>Author</th>
      <th>Title</th>
      <th>Isbn</th>
      <th>Avaliability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.author %></td>
        <td><%= item.title %></td>
        <td><%= item.ISBN %></td>
        <td><%= item.avaliability %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item)  if admin? || is_lib? %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }   if admin? || is_lib?  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path   if admin? || is_lib?  %> </br>
<%= link_to "Advanced Search", new_search_path %>

Web/library_app/app/views/items/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

Web/library_app/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @item.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @item.ISBN %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.Description %>
</p>


<%= link_to 'Edit', edit_item_path(@item) if admin? || is_lib?%> |
<%= link_to 'Back', items_path %>